# cloudbuild.yaml
steps:
  # build & push the container image
  - name: gcr.io/kaniko-project/executor:latest
    args:
      ["--cache=true",--compressed-caching=false,"--cache-ttl=48h", "--destination=gcr.io/$PROJECT_ID/node:latest", "--dockerfile=Dockerfile"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      ["beta", "run", "deploy", "node", "--image", "gcr.io/$PROJECT_ID/node", "--region", "us-central1", "--platform", "managed", '--allow-unauthenticated']
